import mongoose, { Schema, Document, Types } from 'mongoose';

export interface IPattern extends Document {
  profileId: Types.ObjectId;
  category: 'habit' | 'attitude' | 'personality';
  summary: string;
  count: number;
  feedbackIds: Types.ObjectId[];
  generatedAt: Date;
}

const patternSchema = new Schema<IPattern>(
  {
    profileId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    category: {
      type: String,
      required: true,
      enum: ['habit', 'attitude', 'personality'],
    },
    summary: { type: String, required: true },
    count: { type: Number, required: true, default: 0 },
    feedbackIds: [{ type: Schema.Types.ObjectId, ref: 'Feedback' }],
    generatedAt: { type: Date, default: Date.now },
  },
  { timestamps: false }
);

// Regenerated by BullMQ worker when new feedback arrives
patternSchema.index({ profileId: 1, category: 1 });

export const PatternModel = mongoose.model<IPattern>('Pattern', patternSchema);
